# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://cdn.cocoapods.org/'
target 'Gallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gallery
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseUI/Storage'
pod 'GoogleSignIn'

source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end

