# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Gallery' do
 
  # Pods for Gallery
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'GoogleSignIn'
pod 'FBSDKCoreKit', '5.8.0'
pod 'FBSDKLoginKit', '5.8.0'
end
